SELECT TARGET.ID id, TARGET.NAME name, TARGET.IS_ACTIVE active FROM (
SELECT ROWNUM AS RN, TT.* FROM (
SELECT ID, NAME, IS_ACTIVE FROM SHARES
WHERE
LOWER(NAME) LIKE LOWER(:filter) ORDER BY NAME ASC) TT) TARGET  WHERE :fromPos <= TARGET.RN AND TARGET.RN <= :toPos